M7R0
I&tcore=6"%&falseGE\[l3%)nvec2ptnGt+6#%%nvecG6.%"tG%"XG%"jG%"iG%'ppartsG%"kG%(p
partsAG%&cnvecG%(ppartsBG%'partsAG%%pp2aG%'partsBGF$F$C1>8$-%%nopsG6#9$>8%""!?(
8&"""FDF:%%trueGC$>8',&FCFD!""FD@$2FA&F>6#FC>F@,&F@FDFMFD>8*7"?(FCFDFDF:FEC$>FH
FI@$FL?(8)FDFDFMFE>FR7$-%#opG6#FR,&*&F:FD,&FYFDFJFDFDFDFHFD>FR-%%sortGFhn?(FCFD
FDF:FE>&8+FN,$&F>6#,(F:FDFCFJFDFDFJ>8,FS?(FCFDFDF:FEC$>FHFI@$2FAFao?(FYFDFDFaoF
E>Fho7$-Fgn6#FhoFin>Fho-F^oFbp>8-7#-%$seqG6$,*&FRFNFDF@FDFCFJFDFD/FC;FDF@>8.7#-
Fip6$,(&FhoFNFDFCFJFDFDF]q>F`q-%'selectG6$%&isposGF`q>8/-&%)combinatG6#%)conjpa
rtG6#F`q-%'RETURNG6#7$-Fgn6#F\r-Fgn6#FfpF$F$F$6#FD%(istcoreGt+6$%$ptnG%"pG6&%"x
GF/%"RG%#i1GF$F$C&>F:FA?(F@FAFD,&9%FDFJFDFE>&FC6#F@-&F"6#%%rvecG6%F>FisF@?(F@FA
FDFhsFEC$>FH-%%modpG6$,&F@FDFDFDFis>F:,(F:FD*$F[t""#FD*&F[tFD&FC6#FHFDFJ@%/F:&F
C6#FA-Fdr6#FE-Fdr6#F%F$F$F$6#F\u%'tcoresGt+6$F`s%"nG6+%%ptnsGF/%"LG%$nmpGF.F_s%
#rrG%&pcoreG%'pcoresGF$F$C%>F:-&F_r6#%*partitionG6#Fis>Fbof*6#F_sF$6$%)operator
G%&arrowGF$-&F"6#F\s6$F>T$F$F$6$F`sF>-Fhq6$FboF:F$F$F$6#F\u%#npGt+F]wF$F$F$F;F$
F$F$6#FD%,addrimthookGt+6&F_sF.F_vF,6(%$lenGF`v%#cjG%#njG%*prenewptnG%'newptnGF
$F$C)>F:FA>F@-&F"6#FjwF=@%2F@Fis>8(7$-FgnF=-Fip6$FA/F1;FD,&FisFDF@FJ>F_yF>>FY-%
(convertG6$F_y%&arrayG>FCFis?(F$FDFDF$2F:*&9&FD9'FDC$@%/F:FA>&FYFN,&FgzFDFDFD@%
/FCFD>FgzFhzC$>FHFI@%2&FYF_uFgzC$>F`[l,&F`[lFDFDFD>FCFH>FgzFhz>F:,&F:FDFDFD-Fdr
6#-Fjy6$FY%%listGF$F$F$6#""%%$nepGt+F]w6%FbsF/F`sF$F$C%>F:FA?(F@FDFDF;FEC$>FC&F
>F\t@$/-Fft6$FCF\uFA>F:Fg[l-Fdr6#F:F$F$F$6#FD%)ptn2rvecGt+F^sF$F$F$7#-Fip6$-F^t
6%F>FisF1/F1;FAFhsF$F$F$6#F\u%+tcoreofptnGt+F^s6$%#kmGF*F$F$C%>F:f*6#F1F$F^wF$-
FftFdwF$F$6$F`sFis>F@7#-Fip6$,&-F^t6%F>Fis-F:Fa^lFD-F^t6%F>Fis-F:6#,&F1FDFDFDFJ
Fg]l-&F"6#F'F\tF$F$F$6#F\u%)ptn2nvecGt+F^sF$F$F$7#-Fip6$,&Fe]lFD-F^t6%F>FisF`_l
FJFg]lF$F$F$6#F\u%(invphi1Gt+6$%'bigvecGF,60%#tcG%$ntcGF_s%#tqGF.%$tqjG%"rG%%nt
qjGF1F`s%%posiGFex%#nnG%%optnGF$F$C*>F:&F>6#FD>F@-F<F^]l>FC7#-Fip6$&F:6#,(F@FDF
_yFJFDFD/F_yF^q>FH&F>6#F\u?(F_yFisFJFDFEC&>FY&FH6#F_y>FR,&F_yFDFJFD>Fbo-F<6#FY@
$2FAFbo?(FhoFboFJFDFEC&>Ffp&FYFbp>F`q-&F"6#%.findhookinposG6&FCFisFRFfp>F\r-&F"
6#F]x6&FCF`qFfpFis>FCF\r>80-FjxFN>817#-Fip6$&FC6#,(FjclFDF_yFJFDFD/F_y;FDFjcl-F
dr6#F]dlF$F$F$6#F\u%'tcrankGt+F^s6(%"hGFbs%"mGF/F.%$lamGF$F$C'>F:f*6#F,F$F^wF$)
,(F>FDFew#FJF\u#FDF\uFD,&FewFD!"$FDF$F$Fc^l>F@FA>FCFix?(FHFDFDFCFEC%>F_y,(FCFDF
HFJFDFD>FY&F>Fabl>F@,&F@FD-Fft6$,&-F:6#,&FYFDFHFJFD-F:6#,&FHFDFJFDFJFisFD-Fdr6#
-Fft6$F@FisF$F$F$6#F\u%(ptnnormGt+F]wF$F$F$-Fjy6$F>%"+GF$F$F$6#FDFaclt+6&F_sF,%
"wGF`s6)F`v%$mnpG%%findGF.%#fjGFdxFexF$F$C+>F:Fix>FY7$Fay-Fip6$FA/F1;FD*&FbzFDF
isFD>FR-Fjy6$FYF\z>F@-F<Fhn>FCFA>FHFD>F_yFA?(F$FDFDF$2FCFbzC$@$/-Fft6$,&&FRF_uF
DFHFJFisFazC$>F_yFH>FC,&FCFDFDFD>FH,&FHFDFDFD-FdrFablF$F$F$6#F^\l%*randpcoreGt+
6$F`s%$numG6&FbsF/%"aGF_vF$F$C'>F:FA?(F@FDFD,&F>FDFJFDFEC%>FC,&-Fft6$-%%randGF$
FisFD-%&truncG6#,$FisFfelFJ>&FHF\tFC>F:,&FCFDF:FD>&FHF=,$F:FJ>FH7#-Fip6$&FH6#F.
/F.;FDF>-Fb_lF_uF$F$F$6#F\u%&tquotGt+6$F_sF,6-%$npsG%%ptnzG%*lambdabarG%'lamhat
GF/%'muibarG%(lamhatiGF.%#kiGF1%$nikGF$F$C(>F:Fix>F@7$-Fip6$&F>6#,(F:FDFboFJFDF
D/Fbo;FDF:-Fip6$FA/F_y;FDFis>FC7#-Fip6$,&&F@6#FboFDFboFJ/Fbo;FD,&F:FDFisFD>FHFS
?(F_yFAFDFhsFEC(>FYFS>FRFS?(FboFDFDFj^mFE@$/-Fft6$&FCFg^mFisF_y>FY7$-FgnFfblFe_
m>FhoFebl?(FfpFDFD,&FhoFDFJFDFEC$>F`q,(-%&floorG6#*&&FYFjrFDFisFJFD-F``m6#*&&FY
6#,&FfpFDFDFDFDFisFJFJFJFD@$2FAF`q>FR7$Ffn-Fip6$Ffp/Fbo;FDF`q>FH7$-FgnF_uFR-Fdr
F_uF$F$F$6#F\u%#lpGt+F]wF$F$F$&F>6#-FjwF=F$F$F$6#FD%%PHI1Gt+F^s6%%$tcrG%$tquG%$
bgvGF$F$C&>F:-&F"6#Fj]l6$F>Fis>F@-&F"6#Ff\mFhbm>FC7$F:F@-FdrFNF$F$F$6#F\uF`tt+6
%F_sF`sF16&FbsF]elFj`lF.F$F$C&>F:FA>FCFix?(F@FDFDFCFEC$>FH,(FCFDF@FJFDFD>F:,&F:
FD-Fb[m6#*&,&&F>F_uFD-Fft6$,(FisFDF@FJFazFJFisFDFDFisFJFDF]]lF$F$F$6#""$F$,
I(freqtabt+6#F_v6&%%fsetGF/%"MGF.F$F$C%>F:<"?(F@FDFDF;FEC$>F:-%&unionG6$F:<#Fg
\l@%-%%typeG6$&FC6#Fg\l%(integerG>F[fm,&F[fmFDFDFD>F[fmFD?&FHF:FE-%'lprintG6$FH
F^uF$F$F$6#FDF$,
I&ispost+6#F\vF$F$F$@%2FAF>FEF%F$F$F$6#FDF$
