M7R0
I'bailey=6"%&falseGE\[l'%)betafindGt+F$6(%"xG%"jG%"aG%"qG%&alphaG%"nGF$F$C$-%)r
equiresG6#%(qseriesG@&/9#""!C(-I'printfG6$%*protectedG%(_syslibG6#Qen----------
-----------------------------------------------|+F$-F;6#Q7betafind(a,q,alpha,n)
|+F$-F;6#QX~~~This~proc~is~used~to~find~beta~given~alpha~so~that~|+F$-F;6#QC~~~
(alpha,beta)~is~a~Bailey~pair.|+F$-F;6#Q8~~~It~returns~beta[n].|+F$F:/F7""%C)>8
&&9"6#""">8'&FS6#""#>8(&FS6#""$>8)&FS6#FN>8$F8?(8%F8FUF[o%%trueG>F_o,&F_oFU*(-F
fn6%FQFWFaoFU-%'aqprodG6%FWFW,&F[oFUFao!""F\p-Fio6%*&FQFUFWFUFW,&F[oFUFaoFUF\pF
U-%'RETURNG6#-%)simplifyG6#F_oF$F$F$6#F8%'betaupGt+F$6(F,F-%%betaGF/F*F+F$F$C$F
1@&F6C*F:-F;6#Q4betaup(a,q,beta,n)|+F$-F;6#QX~~~This~proc~is~used~to~move~right
~in~~a~Bailey~chain.|+F$-F;6#Q9~~~In~the~Bailey~chain~|+F$-F;6#QX~~~..~->~(alph
a[n],beta[n])~->~(alpha'[n],beta'[n])~->|+F$-F;6#QK~~~this~proc~returns~beta'[n
]~given~beta.|+F$-F;6#QQ~~~As~usual~we~have~assumed~rho1,rho2=infinity.|+F$F:FM
C)>F_oFR>FaoFX>FQFgn>FWF\o>FfnF8?(F[oF8FUFWFbo>Ffn,&FfnFU**)F_oF[oFU)Fao*&F[oFU
F[oFUFU-FQ6%F_oFaoF[oFU-Fio6%FaoFao,&FWFUF[oF\pF\pFU-Fbp6#FfnF$F$F$6#F8%)betado
wnGt+F$FjpF$F$C$F1@'F6C*F:-F;6#Q6betadown(a,q,beta,n)|+F$-F;6#QV~~~This~proc~is
~used~to~move~left~in~a~Bailey~chain.|+F$Feq-F;6#Qjn~~~..~->~(alpha[n]^(-1),bet
a[n]^(-1))~->~(alpha[n],beta[n])~->|+F$-F;6#QO~~~this~proc~returns~beta[n]^(-1)
~given~beta.|+F$F^rF:FMC)>F_oFR>FaoFX>FQFgn>FWF\o>FfnF8?(F[oF8FUFWFbo>Ffn,&FfnF
U*,)F\pFbsFU)F_o,$FWF\pFU)Fao,&*&,(FWFUF[oF\pF\pFUFUFbsFU#FUFZ*$FWFZF\pFUF`sF\p
F^sFUFU-Fbp6#-FepFds-%&ERRORG6#%6nargs~must~be~0~to~4.GF$F$F$6#F8%*alphadownGt+
F$6(F,F-F.F/F*F+F$F$C$F1@'F6C*F:-F;6#Q8alphadown(a,q,alpha,n)|+F$F^tFeqFat-F;6#
QQ~~~this~proc~returns~alpha[n]^(-1)~given~alpha.|+F$F^rF:FMC'>F_oFR>FaoFX>FQFg
n>FWF\o-Fbp6#*(-FQ6%F_oFaoFWFU)F_oFWF\p)Fao*&FWFUFWFUF\pF]vF$F$F$6#F8%(alphaupG
t+F$6&F,F-F.F/F$F$C$F1@&F6C*F:-F;6#Q6alphaup(a,q,alpha,n)|+F$FbqFeqFhq-F;6#QM~~
~this~proc~returns~alpha'[n]~given~alpha.|+F$F^rF:FMC'>F_oFR>FaoFX>FQFgn>FWF\o-
Fbp6#*(FhwFU)Fao*&FWFUFWFUFUFfwFUF$F$F$6#F8%*alphafindGt+F$6(F*F+F,F-F[qF/F$F$C
$F1@'F6C(F:-F;6#Q7alphafind(a,q,beta,n)|+F$-F;6#QX~~~This~proc~is~used~to~find~
alpha~given~beta~so~that~|+F$FG-F;6#Q9~~~It~returns~alpha[n].|+F$F:FMC(>FQFR>FW
FX>FfnFgn>F[oF\o>F_oF8@%/F[oF8-Fbp6#-Ffn6%FQFWF8C$?(FaoF8FUF[oFbo>F_o,&F_oFU*,-
Fio6%F_pFW,(F[oFUFaoFUF\pFUFU)F\pF[pFU)FW,$*&F[pFU,(F[oFUFaoF\pF\pFUFUFhuFUFfoF
UFhoF\pFU-Fbp6#-Fep6#*&F_oFU,&FUFU*&FQFU)FW,$F[oFZFUF\pFUF]vF$F$F$6#F8F$
